spring.application.name=CivilianShield
server.port=${PORT}
spring.datasource.url=jdbc:h2:mem:civilianshield
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a597de001@smtp-brevo.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true